version: "3"
services:
  user_service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    ports:
      - 8888:80
    # environment:
    #   - EXTERNAL_API_URL=https://jsonplaceholder.typicode.com/users